algoritmo "exe3"
// Função :
// Autor :
// Data : 01/08/2019
// Seção de Declarações 
var
   num1, num2, num3, num4 :inteiro
   media:real
inicio
     Escreva("O 1° numero")
     leia(num1)
     Escreva("O 2° numero")
     leia(num2)
     Escreva("O 3° numero")
     leia(num3)
     Escreva("O 4° numero")
     leia(num4)
        media <- (num1 + num2 + num3 + num4)/4
     Escreva("A media é", media)



fimalgoritmo
