algoritmo "exe3"
// Função :
// Autor :
// Data : 03/06/2019
// Seção de Declarações 
var
     num1 , num2, num3, num4:inteiro
     media:real

inicio
    Escreval("o 1° . numero:")
    leia(num1)
    
    Escreval("o 2° . numero:")
    leia(num2)
    
    Escreval("o 3° . numero:")
    leia(num3)
    
    Escreval("o 4° . numero:")
    leia(num4)

       media <-(num1 + num2 + num3+ num4)/4
       Escreva("A media é:",media)



fimalgoritmo
