algoritmo "media_ALuno"
// Função :
// Autor :
// Data : 23/08/2019
// Seção de Declarações
var
n1, n2, n3: real
media: inteiro

inicio
Escreva("Digite a primeira nota:")
leia (n1)

Escreva("Digite a segunda nota:")
leia (n2)

Escreva("Digite a terceira nota:")
leia (n3)


 media = (n1+n2+n3)/3

Se  m > 7 ENTAO
   Escreva("Aluno aprovado")
Senao
   Escreva("Aluno reprovado")

 FIMSE



fimalgoritmo
